steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=kaichuio_ida_rsa.enc
      - --plaintext-file=/root/.ssh/kaichuio_ida_rsa
      - --location=global
      - --keyring=kaichuio
      - --key=github-key
    volumes:
      - name: ssh
        path: /root/.ssh

  - name: gcr.io/cloud-builders/git
    entrypoint: bash
    args:
      - -exc
      - |
        chmod 600 /root/.ssh/kaichuio_ida_rsa
        
        # Add github.com to known hosts to prevent failure
        ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts
        
        # Add key to github.com config
        cat <<EOF >/root/.ssh/config
        Hostname github.com
        IdentityFile /root/.ssh/kaichuio_ida_rsa
        EOF
    volumes:
      - name: ssh
        path: /root/.ssh

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -exc
      - |
        # Cloud Build x GitHub integration uses source archives to fetch
        # the source, rather than Git source fetching, and as a consequence
        # does not include the .git/ directory. As a workaround, we clone
        # the repository and reset it to this build's commit sha.
        git clone 'git@github.com:cage1016/cage1016.github.io.git' tmp        
    volumes:
      - name: ssh
        path: /root/.ssh

  - name: node:12.14.1
    entrypoint: /bin/sh
    args:
      - -exc
      - |
        yarn install
        yarn global add hexo-cli --prefix /usr/local
        hexo clean
        hexo generate
    volumes:
      - name: ssh
        path: /root/.ssh

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -exc
      - |
        cp -rf public/* tmp
        cd tmp
        git add .
        git config user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')
        git commit -m 'Site auto updated by cloudbuild'
        git push origin master
    volumes:
      - name: ssh
        path: /root/.ssh